"""Deterministic multi-agent coordination for Polaris Phase 7."""

from polaris.coordination.errors import (
    AssessmentSourceMismatchError,
    CoordinationCompatibilityError,
    CoordinationError,
    CoordinationValidationError,
    DuplicateAgentDomainError,
)
from polaris.coordination.models import (
    AgreementType,
    ClaimDomainMapRecord,
    CoordinatedAssessment,
    CoordinationAgreement,
    CoordinationCoverageStatus,
    CoordinationDivergence,
    CoordinationFinding,
    CoordinationFindingCode,
    CoordinationProvenance,
    CoordinationRequest,
    DivergenceType,
    DomainCoverageRecord,
    DomainGap,
    DomainGapType,
    DomainRelevanceReference,
    EvidenceDomainMapRecord,
    EvidenceGap,
    EvidenceGapType,
    SharedLimitationRecord,
    UnsupportedInferenceAggregation,
)
from polaris.coordination.service import coordinate_assessments

__all__ = [
    "AgreementType",
    "AssessmentSourceMismatchError",
    "ClaimDomainMapRecord",
    "CoordinatedAssessment",
    "CoordinationAgreement",
    "CoordinationCompatibilityError",
    "CoordinationCoverageStatus",
    "CoordinationDivergence",
    "CoordinationError",
    "CoordinationFinding",
    "CoordinationFindingCode",
    "CoordinationProvenance",
    "CoordinationRequest",
    "CoordinationValidationError",
    "DivergenceType",
    "DomainCoverageRecord",
    "DomainGap",
    "DomainGapType",
    "DomainRelevanceReference",
    "DuplicateAgentDomainError",
    "EvidenceDomainMapRecord",
    "EvidenceGap",
    "EvidenceGapType",
    "SharedLimitationRecord",
    "UnsupportedInferenceAggregation",
    "coordinate_assessments",
]
